[package]
name = "crawfish"
version = "0.0.1"
edition = "2024"

[features]
bench-support = []

[dependencies]
ariadne = "0.4"
ena = "0.14.4"
inkwell = { version = "0.9.0", features = ["llvm22-1"] }
soup = { git = "https://github.com/simontran7/soup" }

[dev-dependencies]
insta = { version = "1", features = ["glob"] }
criterion = "0.8.2"

[[bench]]
name = "tokenizer"
harness = false
required-features = ["bench-support"]